default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: expenses_controller_development

test:
  <<: *default
  database: expenses_controller_test

production:
  <<: *default
  database: expenses_controller_production
  username: expenses_controller
  password: <%= ENV["EXPENSES_CONTROLLER_DATABASE_PASSWORD"] %>
